### ISSUE TITLE
empty add contact dialog

### ISSUE THREAD

**Issue by quiricada** [back2arie/Kalkun#175] opened 2016-09-21 06:58 UTC
i was getting an empty add contact dialog box at
Phonebook >> + Add Contact >> Using contact form

in postgresql log
kalkun@kalkun ERROR:  invalid input syntax for integer: "" at character 41
kalkun@kalkun STATEMENT:  SELECT *
        FROM "pbk_groups"
        WHERE "ID" = ''
        AND "id_user" = '1'

/kalkun/application/views/js_init/phonebook/js_phonebook.php
```
        if($(this).hasClass('addpbkcontact')) {
            var pbk_title = '<?php echo lang('tni_contact_add'); ?>';
            var type = 'normal';
            var param1 = '<?php echo (isset($group_id))? $group_id : "";?>';
        }  
        else if($(this).hasClass('editpbkcontact')) {
            var pbk_title = '<?php echo lang('tni_pbk_edit_contact'); ?>';
            var type = 'edit';
            var param1 = $(this).parents("tr:first").attr("id");
        }
```

modified
            var param1 = `<?php echo (isset($group_id))? $group_id : "";?>`';
to
            var param1 = `<?php echo (isset($group_id))? $group_id : "1";?>`;

**Comment by tenzap** [comment] 2020-05-06 19:09
Duplicate of #238 which has been fixed by PR #240
I think this one can be closed

**Closed** 2021-12-09 06:28 UTC
Labels: bug, archive
