### ISSUE TITLE
rest_api plugin

### ISSUE THREAD

**Issue by MorfeiSYS** [back2arie/Kalkun#484] opened 2022-12-13 19:39 UTC
Hello, when I try to use the rest_api plugin, I get an error
```
An uncaught Exception was encountered
Type: Error

Message: Attempt to assign property "db" on null

Filename: /var/www/htdocs/application/plugins/rest_api/libraries/REST_Controller.php

Line Number: 105

Backtrace:

File: /var/www/htdocs/application/plugins/rest_api/controllers/Rest_api.php
Line: 27
Function: __construct

File: /var/www/htdocs/index.php
Line: 315
Function: require_once
```

**Comment by tenzap** [comment] 2022-12-18 12:27
What are you trying to do? Please follow the issue guidelines and report your configuration as displayed in the "about kalkun" window.

**Comment by tenzap** [comment] 2023-06-20 09:59
Kalkun will be updated to the latest upstream RestController in #493 .

I couldn't reproduce your problem with it. You may try again with that update, if it still doesn't work maybe you should check your configuration of the rest_api plugin. There is some clue on the wiki at https://github.com/kalkun-sms/Kalkun/wiki/Plugin%3A-REST-Api#configuration

I'm closing this issue. If you still face problems, please reopen a new issue, follow the issue guidelines, report your configuration as displayed in the "about kalkun" window, and explain what you are trying to do.

**Closed as completed by tenzap** 2023-06-20 09:59 UTC
