### ISSUE TITLE
Not working Delivery report

### ISSUE THREAD

**Issue by trajectoryspb** [back2arie/Kalkun#483] opened 2022-11-09 12:43 UTC
**Describe the bug**
Hello!
We have trouble with delivery reports. Delivery reports does not appears in Kalkun interface, but in Gammu log (gammu-smsd) it exist.
Column DeliveryDateTime.sentitems in DB backend always is NULL while incoming SMS works fine. 
Status : Sending successful - Awaiting report

**Screenshots**
![image (238)](https://user-images.githubusercontent.com/67903757/200832740-256b4352-7106-4c8d-8e1c-8162e2db5e24.png)

**Browser, kalkun setup, database setup..:**
Please open the "about" screen of kalkun and copy/paste the information.
To open the about screen, go to the dashboard and at the bottom right click on the version of kalkun, right after "Powered by..."
- Kalkun version: 0.8.0-rc-1 [Lang: russian] [CountryCode: RU]
- Operating system: Linux sms-server 4.19.0-22-amd64 #1 SMP Debian 4.19.260-1 (2022-09-29) x86_64
- PHP Version: 7.3.31-1~deb10u1
- DB Backend: MySQLi 8.0.30 (mysqli)
- Gammu version & DB Schema: Gammu 1.40.0, Linux, kernel 4.19.0-22-amd64 (#1 SMP Debian 4.19.260-1 (2022-09-29)), GCC 8.2 & 17
- Browser: Chrome 107.0.0.0
- Installed plugins: jsonrpc

**Comment by tenzap** [comment] 2022-11-11 14:58
This table is filled by [gammu/smsd](https://www.wammu.eu), so the problem is more likely to be tha programme rather than in kalkun. We use the field "`Status`" of table "`sentitems`" to output the status.

So if in the database you have "SendingOK" then it is expected kalkun outputs  `Status : Sent, waiting for report`

Here is the place where the label is rendered based on the value on that field
https://github.com/kalkun-sms/Kalkun/blob/v0.8.0/application/helpers/kalkun_helper.php#L146

**Comment by tenzap** [comment] 2022-11-11 15:13
Closing for now. Please reopen if still relevant.

**Closed as completed by tenzap** 2022-11-11 15:13 UTC
